# Generated by Django 4.2.29 on 2026-03-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='trust_score',
            field=models.IntegerField(default=70),
        ),
    ]
